In [1]:
import pandas as pd
import sklearn

In [2]:
data = pd.read_csv('oranapp1.csv')

data

Region  Temp  Rainfall  Humidity  Apples  Oranges
0  Guangyuan    73        67        43      56       70
1      Loudi    91        88        64      81      101
2     Sinnva    87       134        58     119      133
3   Shenzhen   102        43        37      22       37
4  Pingxiang    69        96        70     103      119

In [3]:
input_data = data.iloc[:-1, 1:4]
output_data = data.iloc[:-1, 4:]

print(input_data)
print(output_data)

   Temp  Rainfall  Humidity
0    73        67        43
1    91        88        64
2    87       134        58
3   102        43        37
   Apples  Oranges
0      56       70
1      81      101
2     119      133
3      22       37


## 线性回归——scikit-learn实现

In [4]:
from sklearn import linear_model

lr = linear_model.LinearRegression()
lr.fit(input_data, output_data)

input = [[69,96,70]]
output = lr.predict(input)
print(output)

[[ 98.71937639 119.30003182]]


c:\Users\33398\.conda\envs\pythonProject\Lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


## 线性回归——pyotch实现

In [22]:
from torch.utils.data import TensorDataset,DataLoader
import torch.nn.functional as F
from torch import nn
import  torch

inputs = torch.tensor(input_data.values,dtype=torch.float32)
outputs = torch.tensor(output_data.values,dtype=torch.float32)

train_ds = TensorDataset(inputs,outputs)
train_dl= DataLoader(train_ds,shuffle=True)

loss_fn = F.mse_loss

model = nn.Linear(3,2)
opt = torch.optim.SGD(model.parameters(), lr=10**-5)

predict = model(inputs)

In [23]:
def fit(train_d1,num_epochs, model, loss_fn,opt):
    # 迭代num_epochs次
    for epoch in range(num_epochs):
        # 使用分批数据进行训练
        for xb,yb in train_d1:
            #训练模型
            pred = model(xb)
            # mse损失函数
            loss = loss_fn(pred,yb)
            # 计算梯度，反向传播
            loss.backward()
            # 使用梯度更新参数
            opt.step()

            # 重置梯度为 0

            opt.zero_grad()
        if(epoch+1) % 100 == 0:
            pass
            # print('Epoch [{}/{}], Loss:{:0.4f}'.format(epoch+1,num_epochs,loss.item()))

In [24]:
fit(train_dl,700,model,loss_fn,opt)

print(predict)

tensor([[57.4487,  6.4894],
        [79.1562, 12.5545],
        [96.0733,  5.2211],
        [45.5891,  2.9437]], grad_fn=<AddmmBackward0>)


## 分类问题——scikitlearn

In [28]:
# 鸢尾花分类
import sklearn.datasets
import numpy as np

iris = sklearn.datasets.load_iris()
data = iris.data
target = iris.target

print(data[:5])
print(target[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [34]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

x_train,x_test,y_train,y_test = train_test_split(data,target,test_size=0.2)

lr = LogisticRegression()
lr.fit(x_train,y_train)

print(lr.predict(x_test))
print(y_test)

[0 1 0 2 1 1 1 0 1 2 0 0 2 0 1 2 0 1 1 1 0 1 0 0 2 2 2 0 1 2]
[0 1 0 2 1 1 1 0 2 2 0 0 2 0 1 2 0 1 1 1 0 1 0 0 2 2 2 0 1 2]


c:\Users\33398\.conda\envs\pythonProject\Lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


: 

In [ ]:
print()

## 分类问题——pytorch