In [1]:
#代码清单 4-1-(1)
import numpy as np

In [15]:
#4-1-(2)
a = np.array([2,1])
print(a)

[2 1]


In [3]:
#3
type(a)

numpy.ndarray

In [4]:
#4
c = np.array([[1,2],[3,4]])
print(c)

[[1 2]
 [3 4]]


In [5]:
#5
d = np.array([[1],[2]])
print(d)

[[1]
 [2]]


In [6]:
#6
print(d.T)

print(d.T.T)

[[1 2]]
[[1]
 [2]]


In [7]:
#7
a = np.array([2,1])
b = np.array([1,3])
print(a+b)

[3 4]


In [8]:
#8
a = np.array([2,1])
b = np.array([1,3])
print(a-b)

[ 1 -2]


In [9]:
#9
print(2*a)

[4 2]


In [10]:
#10
b = np.array([1,3])
c = np.array([4,2])
print(b.dot(c))

10


In [11]:
#11
a = np.array([1,3])
print(np.linalg.norm(a))


3.1622776601683795
