In [1]:
#1
import numpy as np

In [2]:
#2
A = np.array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [3]:
#3
B = np.array([[7,8,9],[10,11,12]])
print(B)

[[ 7  8  9]
 [10 11 12]]


In [4]:
#4
print(A+B)
print(A-B)

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]


In [5]:
#5
A = np.array([[1,2,3],[4,5,6]])
print(2*A)

[[ 2  4  6]
 [ 8 10 12]]


In [6]:
#6
A = np.array([1,2,3])
B = np.array([4,5,6])
print(A.dot(B))


32


In [7]:
#7
A = np.array([1,2,3])
B = np.array([4,5,6])
print(A*B)

[ 4 10 18]


In [8]:
#8
A = np.array([1,2,3])
B = np.array([4,5,6])
print(A/B)


[0.25 0.4  0.5 ]


In [9]:
#9 
A = np.array([[1,2,3],[-1,-2,-3]])
B = np.array([[4,-4],[5,-5],[6,-6]])
print(A.dot(B))

[[ 32 -32]
 [-32  32]]


In [10]:
#10
A = np.identity(3)
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
#11
A = np.identity(3)
B = ([[1,2,3],[4,5,6],[7,8,9]])
print(A.dot(B))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [12]:
#12
A = ([[1,2],[3,4]])
B = np.linalg.inv(A)
print(B)
#print(A.dot(B))
#这样的话会报错
print(type(A))
#因为A的类型是list不是array

#尝试修改上面代码
A = np.array([[1,2],[3,4]])
B = np.linalg.inv(A)
print(B.dot(A))
#应该是要A的逆×A

[[-2.   1. ]
 [ 1.5 -0.5]]
<class 'list'>
[[1.00000000e+00 0.00000000e+00]
 [2.22044605e-16 1.00000000e+00]]


In [13]:
#13
A = np.array([[1,2,3],[4,5,6]])
print(A)
print(A.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
